import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'core/services/auth_service.dart';
import 'core/services/console_alert_gateway.dart';
import 'core/services/location_service.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/auth_gate.dart';
import 'features/home/home_screen.dart';
import 'features/sos/sos_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Try to bring up Firebase. Requires platform config generated by
  // `flutterfire configure` (google-services.json / GoogleService-Info.plist).
  // If it's absent we run in dev mode with a console gateway so the UI is still
  // exercisable without a backend.
  bool firebaseReady = false;
  try {
    await Firebase.initializeApp();
    firebaseReady = true;
  } catch (e) {
    debugPrint('Firebase not configured — running in dev mode. ($e)');
  }

  runApp(SurakshaApp(firebaseReady: firebaseReady));
}

class SurakshaApp extends StatelessWidget {
  const SurakshaApp({super.key, required this.firebaseReady});

  final bool firebaseReady;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Suraksha',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      home: firebaseReady ? AuthGate(auth: AuthService()) : const _DevHome(),
    );
  }
}

/// Backendless entry used when Firebase isn't configured: alerts are logged to
/// the console so the SOS/shake/live-share flow can be demoed on any device.
class _DevHome extends StatelessWidget {
  const _DevHome();

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => SosController(
        gateway: ConsoleAlertGateway(),
        locationService: LocationService(),
        currentUserId: 'dev-user',
      ),
      child: const HomeScreen(),
    );
  }
}
